services:
  app:
    image: "spring-boot:latest"
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - lan
    depends_on:
      - db

  db:
    image: "postgres:latest"
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - lan

  keycloak:
    image: "keycloak:latest"
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak_db
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - lan

networks:
  lan:
    driver: bridge

volumes:
  postgres_data:
