services:
  app:
    image: "spring-boot:latest"
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"

  db:
    image: "postgres:latest"
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: