spring.application.name=SpringTrial
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/app_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
gemini.api.key=
