spring.application.name=SpringTrial
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/app_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Wymuszenie strategii dla ciasteczek sesyjnych
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true

# Dodatkowo naprawiamy sesję (musi być dostępna dla wszystkich ścieżek)
server.servlet.session.cookie.path=/
server.servlet.session.cookie.hierarchical=true

# Ważne dla obsługi sesji między portami localhost
server.forward-headers-strategy=framework


spring.security.oauth2.client.registration.keycloak.client-id=system-kredytowy-app
spring.security.oauth2.client.registration.keycloak.client-secret=dupa
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email


spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak.local:8081/realms/system-kredytowy-app
spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak.local:8081/realms/system-kredytowy-app/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://keycloak.local:8081/realms/system-kredytowy-app/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://keycloak.local:8081/realms/system-kredytowy-app/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://keycloak.local:8081/realms/system-kredytowy-app/protocol/openid-connect/certs
